### ISSUE TITLE
Refactor IO/Directory style operations

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/hadrian#163]
We have a number of abstractions over the System.IO/System.Directory functions. These live in both Base and Rules/Actions, have either return type Action or IO. They need cleaning up. Some thoughts:

* Should we use Shell style names, mkdir and rmdir, so they are obviously in a separate namespace to the Haskell ones?
* Should they be in IO or in Action, or in MonadIO?
* What should they trace?
* I assume they should all be as "automatic" as possible, e.g. removing a file that doesn't exist is fine, creating a directory that already exists is fine.

Notes taken from discussions in #156

**Comment by angerman** [comment]
Just my two cents.

> * Should we use Shell style names, mkdir and rmdir, so they are obviously in a separate namespace to the Haskell ones?

:+1: for shell style names.

> * Should they be in IO or in Action, or in MonadIO?

I'd say `Action` so we need fewer `lift`s?

> * What should they trace?

No idea :(

> * I assume they should all be as "automatic" as possible, e.g. removing a file that doesn't exist is fine, creating a directory that already exists is fine.

:+1:

**Comment by snowleopard** [comment]
Here are some of my preferences:
* I would like to keep non-shortened names similar to those in `Shake` and `System`. In some cases this even seems unavoidable because we'd like to distinguish between `copyFile` and `copyDirectory`, but there is only one Shell function `cp` which does both, so we'll have to invent a name anyway. Furthermore, we have functions without direct equivalents, such as `fixFile` or `runBuilder` and we wouldn't want to rename those to `fxf` or `rnbld` for consistency.
* Ideally they should all be `Action`s and live somewhere in `Rules/Actions.hs` or `Actions.hs`. There is only one problem with this: we might want to run some of these functions in `actionFinally` which expects an `IO`.

**Comment by snowleopard** [comment]
> What should they trace?

@ndmitchell I'm not sure I understand exactly what you mean here. Are you referring to Shake's `traced` function used for profile reports?

> I assume they should all be as "automatic" as possible, e.g. removing a file that doesn't exist is fine, creating a directory that already exists is fine.

Yes, this seems reasonable.

**Comment by ndmitchell** [comment]
> What should they trace?

They should all go through `traced`, since that's helpful and not visible. I was more meaning what they should print to the screen - should they go through the boxy thing, or just be silent.

**Comment by snowleopard** [comment]
I see. I think they should be controlled similarly to `build` actions with `--build-info` flag (#134). The only extra detail to consider is that some of these `Actions` print a single line only (e.g. `createDirectory`), so their behaviour should be identical with `--build-info=normal` and `--build-info=brief`.
