### ISSUE TITLE
Build fails with "Invalid cross-device link"

### ISSUE THREAD

**Issue by michalt** [snowleopard/hadrian#236]
Compiling with `./hadrian/build.stack.sh --flavour=quick` fails with:

```
/--------------------------------------------------\
| Move directory                                   |
|      input: /tmp/extra-dir-29996566726/gmp-5.0.3 |
|  => output: _build/stage1/gmp                    |
\--------------------------------------------------/

[...]

Error when running Shake build system:
* inplace/bin/mkUserGuidePart
* OracleQ (PackageDataKey ("_build/stage2/utils/mkUserGuidePart/package-data.mk","_build_stage2_utils_mkUserGuidePart_C_SRCS"))
* _build/stage2/utils/mkUserGuidePart/package-data.mk
* utils/mkUserGuidePart/stage2/package-data.mk
* inplace/bin/ghc-stage2
* inplace/lib/bin/ghc-stage2
* OracleQ (PackageDataKey ("_build/stage1/ghc/package-data.mk","_build_stage1_ghc_C_SRCS"))
* _build/stage1/ghc/package-data.mk
* ghc/stage1/package-data.mk
* OracleQ (PackageDataKey ("_build/stage1/compiler/package-data.mk","_build_stage1_compiler_COMPONENT_ID"))
* _build/stage1/compiler/package-data.mk
* compiler/stage1/package-data.mk
* _build/stage1/gmp/include/ghc-gmp.h
/tmp/extra-dir-29996566726/gmp-5.0.3: rename: unsupported operation (Invalid cross-device link)
```

Note: `/tmp/` is a `tmpfs` on my system (Fedora 24). Seems like moving the directory doesn't work in this situation?

**Comment by michalt** [comment]
Ok, so unless I'm missing something, we're calling `renameDirectory` which calls Posix `rename` and that doesn't work across different filesystems.

**Comment by ndmitchell** [comment]
The problem is https://github.com/snowleopard/hadrian/blob/f0781a7c0c1124d7e0150298ca39b08a849ac338/src/Rules/Gmp.hs#L62-L79 - specifically we use `withTempDir` which creates a temp directory on a different system, then `moveDirectory` at the end. @snowleopard will have to comment on why we do all the operations on a temp directory first then move, rather than doing them directly to the right place in the first instance.

**Comment by snowleopard** [comment]
Thanks for reporting and fixing! It's sad that existing CI instances cannot catch such bugs. Perhaps, we can add a new CI to test commits on Fedora? @michalt Could you help with this?

To explain why I am using a temporary directory: I cannot unpack `libffi-tarballs/libffi-3.2.1.tar.gz` in the way I like just by invoking `tar` with appropriate command line arguments. What I want is all contents to go into `_build/stage1/libffi` without any intermediate directories. If you figure out a way to do that without using temporary directories, please let me know!

**Comment by ndmitchell** [comment]
It doesn't have to be a temp directory though, you can just extract then rename to a known place in the build system. Still unpleasant though.

**Comment by ndmitchell** [comment]
And perhaps add the above as a comment near that code? Its a weird thing to do for sane reasons :)

**Comment by snowleopard** [comment]
@ndmitchell Good idea, I'll add a comment.

I did use just another directory previously, something like `_build/libffi-tarball` but it felt awkward, because it complicated the build tree, hence potentially confusing people. If you think it would be safer to avoid using temporary directories I will switch back to using `_build/libffi-tarball`. In fact I can just delete it, to avoid confusion.

**Comment by ndmitchell** [comment]
I'm not against using the temporary directory. The whole setup is a mess, and I imagine the temp directory is the most robust way of solving it.
