### ISSUE TITLE
Colorcodes in file after piping progress information to file

### ISSUE THREAD

**Issue by thomie** [snowleopard/hadrian#244]
Priority lowest.

Hadrian/Shake progress information is very pretty and colorful. Only problem is, after running `./hadrian/build.sh > build.log`, `build.log` contains not so pretty entries like:

```
 ^[[m^[[97m^[[34m/-------------------------------------------------------------------\
 | Run Ghc Link Stage0 (stage = Stage0, package = genprimopcode)     |
 |      input: _build/stage0/utils/genprimopcode/Main.o (and 4 more) |
 |  => output: inplace/bin/genprimopcode                             |
 \-------------------------------------------------------------------/^[[0m
```

`utils/ghc-pkg/Main.hs` has some code to work around this problem:
```
    is_tty <- hIsTerminalDevice stdout
    if not is_tty
       then mapM_ show_normal stack
       else do tty <- Terminfo.setupTermFromEnv
               case Terminfo.getCapability tty withForegroundColor of
                   Nothing -> mapM_ show_normal stack
                   Just w  -> runTermOutput tty $ mconcat $
                                                  map (show_colour w) stack
```
From GHC commit https://github.com/ghc/ghc/commit/930421d4ed09e5389e0ef4c5eef36075a6809cc0:
```
       Colour support comes from the terminfo package, and is only used when
        - not --simple-output
        - stdout is a TTY
        - the terminal type has colour capability
```

**Comment by Mathnerd314** [comment]
You could pipe it through the [strip-ansi-cli](https://github.com/chalk/strip-ansi-cli) program, or use a text viewer that parses the ANSI codes.

If you really do need a color output option, it should have three values: 'always', 'never', and 'auto' (i.e. tty detection), so that it's still usable with ``less -R``.

**Comment by snowleopard** [comment]
Reopened as we'd like to improve on the current solution.

**Comment by michalt** [comment]
Ok, so to summarize what we still want to do:

- Remove the hack for mingw/cygwin in favor of a way to specify whether the colors should be added always/never/automatically (similar to what `grep` is doing). Should this be a flag or something in `Settings/User.hs`? I'm a bit hesitant about a flag, because shake already has one, so having another might cause some confusion.

- Allow to specify what colors to use (since users might be using dark or light backgrounds, certain color combinations might not work well for them). This should probably go to `Settings/User.hs`?

Anything else?

**Comment by snowleopard** [comment]
@michalt Thanks for the summary. We could probably include here the [remark](https://github.com/snowleopard/hadrian/pull/253#issuecomment-219448135) by @Mathnerd314 that we can/should override Shake's `shakeOutput` in `shakeOptions` for telling Shake how to use colours. I'm not entirely sure what this means, but I think this could help us reuse Shake's `--colour` flag, at least partially.

**Comment by snowleopard** [comment]
I've been experimenting with providing colour settings from `Settings/User.hs` but all my attempts lead to nasty import cycles: we need to import `Settings/User.hs` from the file where `putBuild` et al are defined, but the latter are needed in a lot of places. I managed to solve this by sacrificing `putError` (using plain `error` instead, which should be fine) and a couple of invocations of `putOracle` (where I used `putLoud`). Most probably all oracle output will eventually be replaced with `putLoud`, to be visible only in verbose mode.

**Comment by snowleopard** [comment]
OK, I think I've come up with an OK solution.

We attempt to detect support for colour automatically, but if we fail use `--progress-colour=never` and colours will not be used (this is now used at CI).

Users can change the way `putBuild` and `putSuccess` are printed in `Settings/User.hs`.

**Comment by michalt** [comment]
@snowleopard Works well for me. Thanks!
