### ISSUE TITLE
Fix dynamicGhcPrograms (or not!)

### ISSUE THREAD

**Issue by thomie** [snowleopard/hadrian#248]
`git grep dynamicGhcPrograms` in the `hadrian` repository returns suspiciously few results. I don't think this is working yet.

All `utils` that are shipped with GHC (like `hsc2hs`, `haddock` etc), and also `ghc` itself, should be built `-dynamic`.

Depends on #4 (Fix dynamic way).

**BUT MAYBE IT IS NOT NECESSARY TO IMPLEMENT DYNAMIC_GHC_PROGRAMS**

Because we can make `ghci -fexternal-interpreter` the default. From: https://ghc.haskell.org/trac/ghc/wiki/RemoteGHCi#Motivation:

> It separates the decision about whether to use the dynamic linker for interpreted code from whether GHC itself must be dynamically linked. We could go back to a statically-linked GHC, which should be faster."

Ask @simonmar to be sure.

See also https://ghc.haskell.org/trac/ghc/wiki/DynamicLinkingDebate and https://ghc.haskell.org/trac/ghc/wiki/DynamicGhcPrograms.

**Comment by DemiMarie** [comment]
Problem: currently the debugger does not work with `-fexternal-interpreter`.

**Comment by bgamari** [comment]
Can this be closed now?

**Comment by snowleopard** [comment]
@bgamari Not sure. I think @izgzhen fixed the `dynamic` way (on Linux and Mac) but we have not yet implemented full support for `dynamicGhcPrograms`. Do we need it?

**Comment by bgamari** [comment]
Well, the current default build configuration of the make-based build system is `DYNAMIC_GHC_PROGRAMS=YES` where possible. We could (and perhaps should) reconsider this, but I'd be weary of changing just because the build system doesn't support it. In particular I'm a bit concerned about platforms where the RTS linker isn't terribly robust (e.g. ARM). In this case I fear that we may regress in terms of stability if we change. Consequently I think we should tread carefully.

**Comment by izgzhen** [comment]
then at least it should be a post-merge goal?

**Comment by snowleopard** [comment]
@bgamari @izgzhen Is this issue still relevant?

**Comment by izgzhen** [comment]
not sure, checked the GHC Wiki and it seemed that both pages might be outdated (latest change 3 years ago).

**Comment by snowleopard** [comment]
Let me close this. If this is acually still an issue, I suggest that we open a new one with an up-to-date description of what needs to be done.
