### ISSUE TITLE
Refactor flavours and Haskell optimisation flags

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#268]
While trying to resolve #259 I got completely confused by how optimisation flags work in the Make build system, because `-O`, `-O2` and `-O0` are added to command lines in very convoluted ways, sometimes together, somehow overriding each other.

Let's improve this in Hadrian! Since we now have much better control over what we put into command line, I think we don't even need to use `-O0`.

As a start, please help me fill in the following table (to be further expanded with other flavours).

<table>
  <tr>
    <th rowspan="2">Flavour</th>
    <th colspan="3">Stage0</th>
    <th colspan="3">Stage1</th>
    <th>Stage2</th>
  </tr>
  <tr>
    <td>Libraries</td>
    <td>GHC</td>
    <td>Utils</td>
    <td>Libraries</td>
    <td>GHC</td>
    <td>Utils</td>
    <td>Everything</td>
  </tr>
  <tr>
    <td>Default</td>
    <td>-O</td>
    <td>-O</td>
    <td>-O</td>
    <td>-O2</td>
    <td>-O2</td>
    <td>-O2</td>
    <td>-O2</td>
  </tr>
  <tr>
    <td>Quick</td>
    <td>-O0</td>
    <td>-O</td>
    <td>-O0</td>
    <td>-O</td>
    <td>-O0</td>
    <td>-O0</td>
    <td>-O0</td>
  </tr>
  <tr>
    <td>Quickest</td>
    <td>-O0</td>
    <td>-O0</td>
    <td>-O0</td>
    <td>-O0</td>
    <td>-O0</td>
    <td>-O0</td>
    <td>-O0</td>
  </tr>
</table>

While we are at it, we could also look into `-H32m` vs `-H64m`. Strangely, in Make all flavours use `-H64m`, however the default value in `config.mk.in` is `-H32m`. Why? Shall we reproduce the same in Hadrian?

@simonmar @thomie Please let me know whether the above table is correct.

**Comment by thomie** [comment]
* Stage0 libraries + stage0/1 utils + everything else: `SRC_HC_OPTS`
* Stage0 GHC: `GhcStage1HcOpts`
* Stage1 GHC: `GhcStage2HcOpts`
* Stage1 libraries: `GhcLibHcOpts`

Rts always -O2.

Optimization flags can also come from .cabal files.

Those `-H` flags potentially influence build time. I've never had the time to measure if they actually make a difference. Some ideas in http://mail.haskell.org/pipermail/ghc-devs/2016-January/011206.html. Without measuring, I would either remove it, or use `-H`.

**Comment by snowleopard** [comment]
@thomie Thanks! What keeps confusing me is that both `SRC_HC_OPTS` and `GhcStage1HcOpts` eventually get smashed together in `$1_$2_$3_ALL_HC_OPTS` via a chain of intermediate variables, so somehow the latter overrides the former (is GHC sensitive to the order of optimisation arguments?).

> Optimization flags can also come from .cabal files.

Do I understand correctly that Hadrian should ignore these ones?

What I had in mind is to `builder Ghc ? remove ["-O0", "-O", "-O2"]` all optimisation flags before adding flavour-related flags according to the above table.

**Comment by snowleopard** [comment]
> Rts always -O2.

Correct me if I'm wrong, but `*.c` files in `rts` are compiled with `gcc`, so this discussion does not apply?

**Comment by thomie** [comment]
> is GHC sensitive to the order of optimisation arguments
Yes. Later flag override earlier flags.

The old build system honors .cabal flags. I don't know what happens if you would ignore them, though it might speed up the build for `Quick` and `Quickest`. `libraries/binary/binary.cabal` for example contains `-O2 -fliberate-case-threshold=1000`.

Re: RTS I was just trying to be complete. In the old build system, `.c` files are passed to `ghc`, not to `gcc`. I don't know about Hadrian.
```
 "inplace/bin/ghc-stage1" -optc-fno-stack-protector -optc-Wall -optc-Wall -optc-Wextra -optc-Wstrict-prototypes -optc-Wmissing-prototypes -optc-Wmissing-declarations -op tc-Winline -optc-Waggregate-return -optc-Wpointer-arith -optc-Wmissing-noreturn -optc-Wnested-externs -optc-Wredundant-decls -optc-Iincludes -optc-Iincludes/dist -optc- Iincludes/dist-derivedconstants/header -optc-Iincludes/dist-ghcconstants/header -optc-Irts -optc-Irts/dist/build -optc-DCOMPILING_RTS -optc-fno-strict-aliasing -optc-fn o-common -optc-Irts/dist/build/autogen -optc-Werror=unused-but-set-variable -optc-Wno-error=inline -optc-O2 -optc-fomit-frame-pointer -optc-g -optc-DRtsWay=\"rts_v\" -s tatic  -O -H64m  -Iincludes -Iincludes/dist -Iincludes/dist-derivedconstants/header -Iincludes/dist-ghcconstants/header -Irts -Irts/dist/build -DCOMPILING_RTS -this-pac kage-key rts -dcmm-lint      -i -irts -irts/dist/build -irts/dist/build/autogen -Irts/dist/build -Irts/dist/build/autogen           -O2    -c rts/RtsFlags.c -o rts/dist /build/RtsFlags.o
```

**Comment by snowleopard** [comment]
> Yes. Later flag override earlier flags.

Ah, this makes sense then! 

> The old build system honors .cabal flags.

So, looking at the construction of `$1_$2_$3_ALL_HC_OPTS`, I think `.cabal` flags come from `$1_$2_HC_OPTS`, and they come fairly late in the command line, so they indeed override flavour-specific flags. On the one hand this is a reasonable behaviour, but on the other hand the whole point of `Quick` and `Quickest` flavours is to suppress optimisation as much as possible in favour of quick builds.

Perhaps, we should be taking a bit more intelligent approach: have an ordering `O0 < O < O2` and express flavour-specific settings in the functional form, e.g. `max O` or `min O2`. As an example, in the `Quick` flavour we can use `max O` for Stage1 libraries, which means that unless a particular library has `O0` in its `.cabal` file, we will use `O`; in the `Default` flavour we may want to say `min O` in Stage0 forcing all libraries to be optimised with at least `O` flag (which the `binary` package will override to `O2`). What do you think of this idea?

**Comment by thomie** [comment]
I'm not sure which problem you're trying to solve.

Just let the build flavors override the optimization level specified in .cabal flags. If that turns out to be a problem, because of failing or very slow tests or whatever, go back to the old ordering.

There aren't any .cabal files that specify `-O0`, just some that define `-O2`.

Release builds should use `-O2`.

**Comment by snowleopard** [comment]
> I'm not sure which problem you're trying to solve.
> Just let the build flavors override the optimization level specified in .cabal flags.

I guess I was just trying to solve my own confusion and make it easier to understand how optimisation flags are set. I missed the point that the last `-Ox` flag overrides all previous ones in the command line (I don't think this is in GHC's documentation). If this is a common way of passing optimisation flags I'll just follow it. I do think though that it would be preferable if Hadrian didn't have to rely on the order of flags for overriding, because this makes it more difficult to understand and modify the build system.

I've edited the top post, now including `-O0` as well, because they are needed when we are overriding.

**Comment by simonmar** [comment]
@snowleopard The general principle is that we arrange for the command line to be built from least-specific settings on the left to most-specific settings on the right, so that specific settings override general ones.  In the old build system we set general options in `SRC_HC_OPTS` and then override those with more specific settings e.g. in `GhcStage2HcOpts`.

I'm not familiar enough yet with the Hadrian codebase to comment on if/how this idea should fit in.

**Comment by snowleopard** [comment]
@simonmar Right now (e.g. the above commits) Hadrian follows exactly the same approach by throwing potentially several `-Ox` flags into the same command line. So, we have:
```haskell
getArgs :: Expr [String]
getArgs = fromDiffExpr $ mconcat [ defaultBuilderArgs
                                 , defaultPackageArgs
                                 , flavourArgs
                                 , userArgs ]
```
This works, but feels unsatisfactory. I don't have a clearly formulated general solution, but I think it would be better if Hadrian had a vocabulary to talk explicitly about the optimisation level, computing it from various sources with a plain function, instead of relying on the order of arguments. That function could directly match the above table, making it obvious which flags are used when.

**Comment by simonmar** [comment]
@snowleopard The left-to-right overriding behaviour is important for other things besides optimisation.  For example, if we're using `-Wall` (which validate does), then we sometimes want to override that on a package-local basis with a `-fno-warn-name-shadowing` or whatever.  We sometimes override the global optimisation settings for a single module or package, for example see https://phabricator.haskell.org/diffusion/GHC/browse/master/compiler/ghc.mk;e170d19702504dd80c2d19f63322c6a219d65f8d$368-370

So I'm not sure I'm keen on having something special for optimisation flags.  The same argument would apply to other types of flags too.

Can we encode the table above in the definition of the flavours?  Actually I kind of liked the way in the old build system that flavours were not a built-in concept but just correspond to a collection of settings that you can use as a basis for your own build.

I'd like to see flavours be defined as `Args` values in modules provided by Hadrian, and then `getArgs` should be defined in `UserSettings.hs` like this:

```
module UserSettings (getArgs) where
import Settings.Flavours.Quick as Quick
getArgs = defaultArgs <> Quick.args
```

woudln't that work?

**Comment by ndmitchell** [comment]
My default advice for converting large build systems is convert as is, rather than trying to optimize/improve simultaneously. Once everyone in GHC world has switched, then we can improve various aspects. However, in this case, I'm not sure having multiple optimisation flags on one command line is any problem at all - in fact it's fairly standard in almost all build systems. You also have to be careful that things like `-O1 -fliberate-case-threshold=50 -O2` might not be quite as simple as a single package of optimisation flags.

**Comment by simonmar** [comment]
I've been thinking about this a bit more.  The way command-line flags are set in Hadrian is quite different from the way it was done in the old build system, and it's not going to be easy to replicate the behaviour of the old build system identically.  The old build system had a number of different mechanisms, which interact in subtle ways, but which are together quite flexible.  Replicating that will be quite difficult and not clean, but we do want to keep the functionality (if not the mechanisms).

There are multiple ways to override fags in the old build system:
* flavours set `SRC_HC_OPTS` directly, overriding the default setting.
* anywhere at all we can set `<filename>_dist_install_HC_OPTS` and that overrides `SRC_HC_OPTS`.
* `EXTRA_HC_OPTS` overrides everything else, because it occurs on the right on the command line

In Hadrian, this defines how flags override each other:

```
getArgs = fromDiffExpr $ mconcat [ defaultBuilderArgs
                                 , defaultPackageArgs
                                 , flavourArgs
                                 , userArgs ]
```

But the consequences of this are:

* We cannot specify module-specific flags in `defaultPackageArgs` that override things in `flavourArgs`.  This is the biggest problem.
* We will always get multiple optimisation flags, because we can't //replace// the settings in `defaultBuilderArgs`, only override them with other flags.  I know there's `remove`, but it gives me a really bad feeling.

Before we think about how to fix this, am I right here or am I missing something?

**Comment by snowleopard** [comment]
> The left-to-right overriding behaviour is important for other things besides optimisation. [...] So I'm not sure I'm keen on having something special for optimisation flags. The same argument would apply to other types of flags too.

@simonmar I'm not saying optimisation flags should be special. I'd prefer **all** kinds flags to be computed directly instead of relying on the order in which they appear in the command line intermixed with other flags. Wouldn't it make life easier if all optimisation-related logic was in one place in the form of _''Here are default optimisation flags for each flavour; here is how to combine them with cabal options; here are some special cases; and by the way, let the user override everything"_? Same for warnings, and other kinds of flags that are logically related.

> My default advice for converting large build systems is convert as is, rather than trying to optimize/improve simultaneously.

@ndmitchell So, here is how Make-to-Shake conversion works in my case: I spend a huge amount of time to understand some aspects of the existing system, e.g. how optimisation flags work, and try to somehow systematise and record what I discovered. Having done that, it feels only natural to implement this in Hadrian in such a way that the person who comes to the codebase next doesn't have to spend the same amount of time to understand how it works. Clear implementation trumps the best documentation in my opinion. And we don't even seem to have any documentation at the moment, let's take your example:

> `-O1 -fliberate-case-threshold=50 -O2`

Is this equivalent to `-fliberate-case-threshold=50 -O2`? Does it make sense to combine  `-fliberate-case-threshold=50` with `-O2`? If not, maybe it's equivalent to simply `-O2`? I have no idea, and I couldn't find this explained anywhere. But I know for sure that we can easily generate such command line both in the old build system and in Hadrian, which presumably can lead to hard to understand bugs.

**Comment by snowleopard** [comment]
> I'd like to see flavours be defined as Args values in modules provided by Hadrian, and then getArgs should be defined in UserSettings.hs like this:
```haskell
module UserSettings (getArgs) where
import Settings.Flavours.Quick as Quick
getArgs = defaultArgs <> Quick.args
```
> woudln't that work?

@simonmar Sure, that would work fine for `Args`, but flavours affect other settings like `Ways`, so if we go this way, then `UserSettings` may become a bit cluttered with flavour-related logic. That is, to change a flavour, the user will have to edit the file in several places.

Another issue with this approach is that for CI we need to be able to set a flavour from the command line. How do you think we should do it then?

**Comment by simonmar** [comment]
> Wouldn't it make life easier if all optimisation-related logic was in one place in the form of ''Here are default optimisation flags for each flavour; here is how to combine them with cabal options; here are some special cases; and by the way, let the user override everything"? Same for warnings, and other kinds of flags that are logically related.

We have a choice between:
* Have everything related to optimisation flags in one place
* Have everything related to a flavour in one place

The old build system does it the latter way, and I have to say it feels more modular to me that way.  I'm surprised to see flavour-related logic spread around various places in Hadrian - I think of a flavour as just a collection of settings that modify the defaults.  In the old build system, when I want to see what changes the "quick" way makes to the default setup, I look in one place.  When I want to add my own flavour (which I do, it's a standard workflow) I copy the quick flavour and make my own tweaks.

But I'm aware this is going against the grain in Hadrian, it's just not designed this way.  I can't work out whether I feel uneasy about the approach that Hadrian takes to modularity because I'm used to the old build system, or because it really would be better done differently.

> Another issue with this approach is that for CI we need to be able to set a flavour from the command line. How do you think we should do it then?

Somehow the information from the command-line flags needs to make it down into `getArgs` so we can add the flavour-related settings, that doesn't seem too hard.

**Comment by snowleopard** [comment]
> The old build system does it the latter way, and I have to say it feels more modular to me that way. I'm surprised to see flavour-related logic spread around various places in Hadrian - I think of a flavour as just a collection of settings that modify the defaults. In the old build system, when I want to see what changes the "quick" way makes to the default setup, I look in one place.

@simonmar Wait, but this is exactly what we have in Hadrian too. File `src/Settings/Flavours/Quick.hs` is supposed to be a direct equivalent of `mk/flavours/quick.mk`. (Note: some flavour-specific settings are not yet implemented.)

> Somehow the information from the command-line flags needs to make it down into getArgs so we can add the flavour-related settings, that doesn't seem too hard.

Yes, Hadrian does that already, here is the corresponding piece of code (see `src/Settings/Ways.hs`):
```haskell
flavourLibraryWays :: Ways
flavourLibraryWays = case cmdFlavour of
    Default  -> mempty
    Quick    -> quickFlavourWays
    Quickest -> quickestFlavourWays
```
But I don't see how to do it if we have `getArgs = defaultArgs <> Quick.args` in `UserSettings` as you suggest. How do we combine the ability to set build flavour from command line (for CI), as well as to set it in `UserSettings`?

**Comment by snowleopard** [comment]
> In Hadrian, this defines how flags override each other:
```haskell
getArgs = fromDiffExpr $ mconcat [ defaultBuilderArgs
                                 , defaultPackageArgs
                                 , flavourArgs
                                 , userArgs ]
```
> But the consequences of this are:
> * We cannot specify module-specific flags in `defaultPackageArgs` that override things in `flavourArgs`. This is the biggest problem.
> * We will always get multiple optimisation flags, because we can't //replace// the settings in `defaultBuilderArgs`, only override them with other flags. I know there's `remove`, but it gives me a really bad feeling.
>
> Before we think about how to fix this, am I right here or am I missing something?

@simonmar I think you are right, there is a problem worth discussing.

Let me come back to your bullet points:

> * We cannot specify module-specific flags in `defaultPackageArgs` that override things in `flavourArgs`. This is the biggest problem.

We can, if we move `flavourArgs` before `defaultPackageArgs`. Shall we do that? Maybe, I'm not sure.

> * We will always get multiple optimisation flags, because we can't //replace// the settings in `defaultBuilderArgs`, only override them with other flags. I know there's `remove`, but it gives me a really bad feeling.

Actually, we can do whatever we want with command lines; `append` and `remove` are just two simplest functions that are already there. Adding `replace` is not hard at all: we just need to implement a function `replace` that given a list of strings, finds and replaces a given string with another one, and then do `apply replace` to `Args`. Here is relevant code from `src/Expression.hs`:
```haskell
-- Basic operations on expressions:
-- | Transform an expression by applying a given function.
apply :: (a -> a) -> DiffExpr a
apply = return . Diff

-- | Append something to an expression.
append :: Monoid a => a -> DiffExpr a
append x = apply (<> x)

-- | Remove given elements from a list expression.
remove :: Eq a => [a] -> DiffExpr [a]
remove xs = apply $ filter (`notElem` xs)
```
Is this what you are after? Let's keep discussing this! Although it may be more productive to do it via Skype or something :-)

**Comment by simonmar** [comment]
Please bear with me, I am gradually understanding more about how Hadrian fits together...

> @simonmar Wait, but this is exactly what we have in Hadrian too. File src/Settings/Flavours/Quick.hs is supposed to be a direct equivalent of mk/flavours/quick.mk. (Note: some flavour-specific settings are not yet implemented.)

Well ok, but I was referring to things like this in `Settings/Ways.hs`:

```
flavourLibraryWays :: Ways
flavourLibraryWays = mconcat
    [ cmdFlavour == Quick ? quickFlavourWays ]
```

This feels wrong, because (a) we have flavour-related logic in a core part of the system, and (b) the set of flavours doesn't seem very user-extensible.

> We can, if we move flavourArgs before defaultPackageArgs. Shall we do that? Maybe, I'm not sure.

But that would just give us the converse problem: now I cannot override anything in `defaultPackageArgs` with `flavourArgs`.

The problem is that we want to do both things:
* have per-package flags that override flavour opts, e.g. setting -O0 for the parser in GHC
* have flavour opts that override per-package flags: e.g. we turn off certain warnings on a per-module basis in validate 

If we only have left-to-right ordering as our overriding mechanism, then I don't see any alternative to having multiple sets of `flavourArgs`.  Maybe that's the right thing to do, but it just seems a bit horrible.

> (replace/append/remove) Is this what you are after?

No, not really :)  I find this quite a troubling abstraction.  Composition via concatenation is straightforward - I can look at the result and every part of the input is there.  Its interpretation is simple, things to the right override things to the left.  However, if things on the right can apply arbitrary transformations to things on the left, then it'll be really difficult to debug how we ended up with a particular command line.

**Comment by snowleopard** [comment]
> Please bear with me, I am gradually understanding more about how Hadrian fits together...

Please bear with me too, I am gradually understanding more about subtleties of Hadrian customisation :-)

> This feels wrong, because (a) we have flavour-related logic in a core part of the system, and (b) the set of flavours doesn't seem very user-extensible.

I'm not sure I fully understand what you mean. Users can add new flavours (collections of user-defined arguments, ways, etc.) in `UserSettings.hs` and switch between them by editing the file. What they can't do at the moment is add new command line flags for activating these flavours from command line. 

One possible way to redesign flavours and make them easier to manage and understand is to create a datatype `Flavour`, which puts all customisation bits together:
```haskell
-- src/Flavour.hs
data Flavour = Flavour
	{ flavourName :: String
	, flavourArgs :: Args
	, flavourWays :: Ways
	, flavourEtc  :: Etc }

-- Definitions of standard flavours
quick :: Flavour
quick = Flavour "quick" quickFlavourArgs quickFlavourWays quickFlavourEtc

-- Users can create new flavours in src/UserSettings.hs
simon1 :: Flavour
simon1 = Flavour "simon1" ...

-- A universe of existing user flavours, to support command line flags like --flavour=simon1
userFlavours :: [Flavour]
userFlavours = [simon1, ...]

-- Choose default flavour
defaultFlavour :: Flavour
defaultFlavour = simon1
```
I think this makes things a lot clearer. Note, with this approach we no longer need separate `userArgs`, `userWays`, etc. in `UserSettings.hs`. They all become fields of user flavour(s).

> The problem is that we want to do both things
> If we only have left-to-right ordering as our overriding mechanism, then I don't see any alternative to having multiple sets of `flavourArgs`. Maybe that's the right thing to do, but it just seems a bit horrible.

Right, I see what you mean now. Multiple sets of `flavourArgs` do look horrible in the current design, but perhaps the `Flavour` datatype can help make things prettier by packaging everything:
```haskell
data Flavour = Flavour
	{ flavourName      :: String
	, flavourArgs      :: Args -- these Args can be overriden by builders, packages, etc.
	, flavourArgsFinal :: Args -- these Args cannot be overriden
	, flavourWays      :: Ways
	, flavourEtc       :: Etc }
```

> No, not really :) I find this quite a troubling abstraction. Composition via concatenation is straightforward - I can look at the result and every part of the input is there. Its interpretation is simple, things to the right override things to the left. However, if things on the right can apply arbitrary transformations to things on the left, then it'll be really difficult to debug how we ended up with a particular command line.

Agreed.

**Comment by snowleopard** [comment]
@simonmar I've got another idea how to provide a way to override `flavourArgs` with `defaultArgs` and vice versa, plus simplify the whole thing a little:
```haskell
data Flavour = Flavour
    { flavourName :: String
    , flavourArgs :: Args
    , flavourWays :: Ways
    , flavourEtc  :: Etc }

simonFlavour :: Flavour
simonFlavour = Flavour "simon" (before <> defaultArgs <> after) defaultWays defaultEtc
```
Now `before` settings can be overridden by default ones, and the latter can be overridden by `after`. 

In this approach there is no hidden glue logic which appends selected `flavourArgs` to `defaultArgs`. This is done by the user explicitly, which gives the full control over how things are combined. This is my current favourite, so unless there are any objections I'll go this way.

**Comment by simonmar** [comment]
I like the idea of being able to compose your own flag settings, however I think we'll need to be a little more fine-grained about it.  We need to have user flags that override defaults (e.g. to change optimisation), and we need to have per-package flags that override user defaults, and finally we need to have user settings that override the per-package settings.  So, something like

```
simonArgs :: Args
simonArgs = defaultBuilderArgs <> before <> defaultPackageArgs <> after

simonFlavour :: Flavour
simonFlavour = Flavour "simon" simonArgs defaultWays defaultEtc
```

I think that should be flexible enough.  Although I think it would be nicer if we could actually directly modify `defaultBuilderArgs` rather than having to rely on left-to-right overriding behaviour on the command line.  I'm thinking something like this:

```
simonArgs :: Args
simonArgs = defaultBuilderArgs BuilderArgs { ghcArgs = ["-O", "-Wall"] }
```

I realise you can do this with the Args monoid, but having a record of the default settings that you can modify is more direct, and it supports tools that don't have overriding semantics on the command line, and it would mean we get fewer superfluous flags in our command lines.

**Comment by snowleopard** [comment]
@simonmar I agree with `defaultBuilderArgs <> before <> defaultPackageArgs <> after`. That's even more transparent and easy to implement.

I'm confused by your second comment though. Are you trying to achieve something like this?
```haskell
simonArgs :: Args
simonArgs = mconcat
    [ defaultBuilderArgs
    , builderGhc ? append ["-O", "-Wall"]
    , defaultPackageArgs ]
```
I guess, the answer is "No"... I don't understand what you mean by "directly modify `defaultBuilderArgs`". GHC has a lot of arguments, so you are not just replacing them with `["-O", "-Wall"]`. So, how exactly are you modifying them in your example?

**Comment by simonmar** [comment]
I was trying to achieve the effect of your example but without having multiple "-O" options on the command line, in a similar way to how flavours work in the old build system when they set `SRC_HC_OPTS`.  This *replaces* the default `SRC_HC_OPTS`, it doesn't add to it.  But let's not spend effort worrying about this unless it's actually a problem.

**Comment by snowleopard** [comment]
@simonmar Thanks, I see. I'm working on refactoring flavours. Currently fighting various import cycles :-S

**Comment by snowleopard** [comment]
OK, I finally pushed a major refactoring of how build flavours and user settings. I couldn't get rid of import cycles, so we now have `src/Settings/Default.hs-boot`.

Users can now do
```haskell
simonFlavour :: Flavour
simonFlavour = defaultFlavour
    { name = "simon"
    , args = defaultBuilderArgs <> before <> defaultPackageArgs <> after
    , ways = defaultWays <> remove [profiling] }

userFlavours :: [Flavour]
userFlavours = [simonFlavour]
```
and then `--flavour=simon` will work. I will also add a way to set a default `Flavour` in `UserSettings`, which by default will be set to `defaultFlavour`.

I need to document this properly in `doc/user-settings.md`.

**Comment by simonmar** [comment]
@snowleopard sounds great, thanks for doing this!  I haven't had much time to look into Hadrian recently but I hope to get to it soon.

**Comment by snowleopard** [comment]
@thomie @simonmar I've translated many build flavours from the old build system to Hadrian and documented them here: https://github.com/snowleopard/hadrian/blob/master/doc/flavours.md. 

If you spot any problems there, please let me know, e.g. by sending a PR to the document (I'll then adapt the code as required).

P.S.: There are a few things that seem strange to me, e.g. why do we optimise things during Stage1 when building in `devel1` flavour? I would suppose that in `devel1` we don't even need to build Stage2 GHC...

**Comment by snowleopard** [comment]
Another unclear point: why the default heap size setting is `-H32` but all build flavours override it with `-H64`?

**Comment by simonmar** [comment]
No good reason, just hysterical raisins.

**Comment by snowleopard** [comment]
@simonmar OK, I've changed everything to `-H32` for now. Makes no difference in my experiments.
