### ISSUE TITLE
runhaskell can't find ghc

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#304]
Go to `inplace/bin` and

```
> ./runhaskell
runhaskell: cannot find ghc
```

This will happen for GHC 65b185d4886b4efa3efe3cc5ecc8dd6e07d89afe and Hadrian 295c7812ab8fe8e34e6812127e039220a850a344 on mu Ubuntu 15.04 machine

**Comment by snowleopard** [comment]
@izgzhen Thanks for reporting!

I can't reproduce this on my Windows machine.

I think the reason is that `runhaskell` requires a wrapper to work correctly.

If someone would like to pick this up, here is where to start:

https://github.com/snowleopard/hadrian/blob/master/src/Rules/Program.hs#L24-L28

**Comment by izgzhen** [comment]
> I think the reason is that runhaskell requires a wrapper to work correctly.

You are right, if I do `./runhaskell -f ./ghc-stage2`, it will be fine.

**Comment by snowleopard** [comment]
@izgzhen Thanks for confirming!

Do you think you could attempt to fix this? It shouldn't be very hard: 
* Add a new wrapper `src/Rules/Wrappers/Runhaskell.hs` (there are some examples in the directory).
* Add the wrapper into the list of `wrappers`, as linked above.

It would be easier for you to test that your fix works.

Otherwise, I'll try to find time to do this over this weekend.

**Comment by izgzhen** [comment]
Yes I am attempting to fix it in a couple of days :) Just need to find some spare time though

**Comment by snowleopard** [comment]
Awesome, thanks! :)
