### ISSUE TITLE
ghc-cabal copy assumes library artifacts in build subpath

### ISSUE THREAD

**Issue by izgzhen** [snowleopard/hadrian#318]
Related `ghc-cabal` code: https://github.com/ghc/packages-Cabal/blob/master/Cabal/Distribution/Simple/Configure.hs#L366

This creates problems for install rules.

We discussed a bit in https://github.com/snowleopard/hadrian/pull/312, but I don't think we have consensus on it yet. Here are several possible ways to fix:

1. Revert the change and build stuff in `build` subpath, as what the old system does.
2. Patch the Cabal source in our build system
3. Add rules for copying or symbolically linking built stuff to `build` (the later one will probably not work on Windows).

The first one is difficult. The second one is a bit hack-ish and will be influenced by upstream code changes. The third one is hash-ish as well, more robust against upstream changes, but a bit wasteful if we have to copy over stuff .....

Overall, I personally favor 2 and propose to do it in a separate PR.

**Comment by snowleopard** [comment]
I think we also discussed another option:

4. Implement the `ghc-cabal copy` functionality in Hadrian.

Presumably, we just need to copy all package objects and the library? It's easy to get a list of all build artefacts that Hadrian produces for a given package. For example, you can get all Haskell objects using this: https://github.com/snowleopard/hadrian/blob/master/src/Oracles/ModuleFiles.hs#L84-L87.

I think this may be the best way to go in the long term. In this way we also have the ability to track files that are being copied, so we'll rebuild outdated files if need be. 

@izgzhen Can you list all the files that need to be copied for a given package, say for `libraries/array`?

**Comment by izgzhen** [comment]
For `libraries/array`:

```
├── Data
│   ├── Array
│   │   ├── Base.dyn_hi
│   │   ├── Base.hi
│   │   ├── IArray.dyn_hi
│   │   ├── IArray.hi
│   │   ├── IO
│   │   │   ├── Internals.dyn_hi
│   │   │   ├── Internals.hi
│   │   │   ├── Safe.dyn_hi
│   │   │   └── Safe.hi
│   │   ├── IO.dyn_hi
│   │   ├── IO.hi
│   │   ├── MArray
│   │   │   ├── Safe.dyn_hi
│   │   │   └── Safe.hi
│   │   ├── MArray.dyn_hi
│   │   ├── MArray.hi
│   │   ├── ST
│   │   │   ├── Safe.dyn_hi
│   │   │   └── Safe.hi
│   │   ├── ST.dyn_hi
│   │   ├── ST.hi
│   │   ├── Storable
│   │   │   ├── Internals.dyn_hi
│   │   │   ├── Internals.hi
│   │   │   ├── Safe.dyn_hi
│   │   │   └── Safe.hi
│   │   ├── Storable.dyn_hi
│   │   ├── Storable.hi
│   │   ├── Unboxed.dyn_hi
│   │   ├── Unboxed.hi
│   │   ├── Unsafe.dyn_hi
│   │   └── Unsafe.hi
│   ├── Array.dyn_hi
│   └── Array.hi
├── HSarray-0.5.1.2.o
├── libHSarray-0.5.1.2-ghc8.3.20170413.dylib
└── libHSarray-0.5.1.2.a
```

The problem is that `ghc-cabal` does more than copying over stuff. Here is the related code in `utils/ghc-cabal/Main.hs`.

```haskell
doCopy directory distDir
       strip myDestDir myPrefix myLibdir myDocdir withSharedLibs
       args
 = withCurrentDirectory directory $ do
     let copyArgs = ["copy", "--builddir", distDir]
                 ++ (if null myDestDir
                     then []
                     else ["--destdir", myDestDir])
                 ++ args
         copyHooks = userHooks {
                         copyHook = noGhcPrimHook
                                  $ modHook False
                                  $ copyHook userHooks
                     }

     defaultMainWithHooksArgs copyHooks copyArgs
    where
      noGhcPrimHook f pd lbi us flags
              = let pd'
                     | packageName pd == mkPackageName "ghc-prim" =
                        case library pd of
                        Just lib ->
                            let ghcPrim = fromJust (simpleParse "GHC.Prim")
                                ems = filter (ghcPrim /=) (exposedModules lib)
                                lib' = lib { exposedModules = ems }
                            in pd { library = Just lib' }
                        Nothing ->
                            error "Expected a library, but none found"
                     | otherwise = pd
                in f pd' lbi us flags
      modHook relocatableBuild f pd lbi us flags
       = do let verbosity = normal
                idts = updateInstallDirTemplates relocatableBuild
                                                 myPrefix myLibdir myDocdir
                                                 (installDirTemplates lbi)
                progs = withPrograms lbi
                stripProgram' = stripProgram {
                    programFindLocation = \_ _ -> return (Just (strip,[])) }

            progs' <- configureProgram verbosity stripProgram' progs
            let lbi' = lbi {
                               withPrograms = progs',
                               installDirTemplates = idts,
                               configFlags = cfg,
                               stripLibs = fromFlag (configStripLibs cfg),
                               withSharedLib = withSharedLibs
                           }

                -- This hack allows to interpret the "strip"
                -- command-line argument being set to ':' to signify
                -- disabled library stripping
                cfg | strip == ":" = (configFlags lbi) { configStripLibs = toFlag False }
                    | otherwise    = configFlags lbi

            f pd lbi' us flags
```

The problem is that my previous experience told me the `copy` does more than copying, but I had a hard time trying to understand what is beyond that. It must be something related to registration etc., since if we simply copy things, then the later `register` step will fail (I remember the errors msg is that it can't import certain libraries ... I should really note that error msg down).

**Comment by snowleopard** [comment]
> For `libraries/array`:

Thanks! We can easily locate and copy these files.

> The problem is that my previous experience told me the `copy` does more than copying, but I had a hard time trying to understand what is beyond that. 

I think it would be very useful to understand and document this.

@bgamari @ezyang Could you help? Is there a specification of what `ghc-cabal copy` is supposed to do?

**Comment by ezyang** [comment]
The most long term, sustainable way to get copy functionality is to use the Cabal library. This means that you have to implement the same directory layout which Cabal expects, which means you have to put things in a build subdirectory of your `dist` directory, because this is just "how the dist directory layout works", and lots of tools, Cabal including, make this assumption about layout.

Of course, Hadrian is already in the business of reimplementing the build logic, so it's not entirely unreasonable that it should also be in the business of reimplement the copy logic. In that case, the correct thing to do is look at  `Cabal/Distribution/Simple/Install.hs` and figure out exactly how copy is implemented. Roughly it's like this:

* Copy data files
* Copy Haddock files
* Copy include files
* Copy module interfaces and objects
* Copy libraries (static and shared), possibly stripping if requested

There is not too much. I can say for certain that copy does NOT do any registering, but registration could fail if files are not in the location that Cabal expects. The "smarts" primarily involve figuring out where things should be installed, and it is not surprising that registration fails if you do not install things to the correct places. ghc-cabal makes some modifications to this (`updateInstallDirTemplates`) and also is responsible for applying any of the other parameters it supports, but it doesn't do anything fundamentally different. But you do need to understand what it does, and that involves reading the code.

**Comment by snowleopard** [comment]
@ezyang Many thanks!

If your list covers everything then it shouldn't be difficult to reimplement this functionality in Hadrian. It's not entirely code duplication, because we're using Shake and can therefore track things when copying. Not sure how useful it is for install rules, but that's something we can't achieve by reusing the Cabal library.

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

>
> @bgamari @ezyang Could you help? Is there a specification of what `ghc-cabal copy` is supposed to do?
>
Not as far as I know. On the plus side, this means it is relatively easy to change.

**Comment by izgzhen** [comment]
> The "smarts" primarily involve figuring out where things should be installed

Good point. Before that I tried a plain "copy" with simple filtering but retaining the original structure as it is. Maybe I should check out if it does something else.

Thanks!

**Comment by izgzhen** [comment]
I believed that this could be closed now?

**Comment by snowleopard** [comment]
Yes, looks like this has been resolved!
