### ISSUE TITLE
Test the install rule

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#373]
While working on #345 I risk accidentally breaking the install rule on Linux/Mac OS X. 

Our CI instances seem to be fast enough to afford running the install rule after the test build, and then testing the installed binary.

**Comment by izgzhen** [comment]
Update: currently I test this daily in `default` mode on my http://hadrian-status-dev.zhenzhang.me. I don't think that add CI support for this is easy, considering recent timeouts, but that is certainly a goal.

**Comment by snowleopard** [comment]
@izgzhen Thanks! Can we set it up, so it sends a notification if the previously successful built got broken?

**Comment by izgzhen** [comment]
> Can we set it up, so it sends a notification if the previously successful built got broken?

I think this is possible. However, currently I maintained a `staging` branch on my GitHub namespace, and this build bot will only pull from that branch. The motivation is to only pull in new changes that at least won't break simpler CIs we are currently using.

The build is run on a daily basis, since it can't afford a full build per commit now.

Despite all these, it is a good idea to let it send some notification if there is any bad thing that happened.

**Comment by snowleopard** [comment]
Yes, I currently get pretty quick feedback if my commit breaks Linux or OS X build, but it's difficult to make sure I haven't broken installation on these platforms. I could of course keep looking this up on the Hadrian Wall website, but I keep forgetting :)

**Comment by snowleopard** [comment]
We no longer have the `install` rule, so closing.
