### ISSUE TITLE
Enable building Cabal with parsec

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#395]
As noticed in #393, we missed the following change in GHC build system:

https://github.com/ghc/ghc/commit/36fe21aa3fe5abe1cef0104b20c296ac9385658d

We need to migrate these changes into Hadrian.

**Comment by snowleopard** [comment]
I've added new packages to Hadrian, but I haven't yet switched Cabal to use `parsec` as it seems things are still in motion, and soon `parsec` will not be behind the flag. So, I'll wait until the build is broken.

**Comment by izgzhen** [comment]
Should I put this is The Merge goals?

**Comment by snowleopard** [comment]
Yes, I think it would be useful to settle this before merging. It's probably not a lot of code, but it will require an investigation on what exactly needs to be done.

**Comment by angerman** [comment]
I've tried this in #445, it ends up being rather annoying, due to the automagic logic with builder arguments.

You end up wanting to add all kinds of packages to `ghc-cabal`. And the `cbits` text, generating the Lexer with alex is less of an issue.

Now, you don't have ghc-cabal, but you start querying the `package-data.mk` for various packages (e.g. text) to figure out ccFlags, and others. However to generate the `package-data.mk` you need ghc-cabal. In #445, I started rolling parts of ghc-cabal into hadrian, but only tiny parts yet.

This would however require that Hadrian was built with Cabal/Cabal from source with `-fparsec`.
I believe this might be the better path to choose, primarily because it would get tracking of dependencies right. Otherwise you end up needing to depend on all source files of packages outside of ghc-cabal, to ensure that ghc-cabal is rebuilt whenever any of the dependent libraries files is changed. (Example: hacking on Cabal in GHC, while working on GHC. E.g. you need features of the bleeding edge Cabal library, because you want to implement something in GHC / GHCs build system.)

**Comment by snowleopard** [comment]
> This would however require that Hadrian was built with Cabal/Cabal from source with `-fparsec`.

Note: Hadrian is already built with Cabal/Cabal from the GHC tree. If I understand you correctly, we'll also need to add `../libraries/parsec` as an extra source directory?

I can see how hacking on Cabal may be problematic, because you may need to rebuild Hadrian itself in this case. That's something I've never previously thought about.

**Comment by angerman** [comment]
> I can see how hacking on Cabal may be problematic, because you may need to rebuild Hadrian itself in this case.

I don't think this would be much on an issue actually when invoking hadrian via the build script, as cabal should keep proper track of the changed files anyway. If seemingly does not currently, but that might be because my bootstrap cabal is using sandboxes and there might be some subtle issue.

The way forward is definitely cabal new-build. And I believe that new-build would track this correctly.
As such, I would maybe add a warning message to the shell script, that tracking of changes to the Cabal library will *not* work when using cabal 1.x. However we should definitely confirm that the bug is with the sandboxes, prior to doing so.

**Comment by snowleopard** [comment]
> when invoking hadrian via the build script, as cabal should keep proper track of the changed files anyway

Oh, that's clever! Sounds even suspiciously too clever at first glance, but I think it should work indeed.

**Comment by angerman** [comment]
Ok. So with cabal new-build, this seems to actually work. When ever my `libraries/Cabal/Cabal` change, cabal does the tracking right and rebuilds hadrian.

I believe I'm going to just try and roll `ghc-cabal` into `hadrian` at this point. That would also relieve the issues with trying to build `ghc-cabal` with `-DPARSEC`. However, I still believe the inability to do this trivially is a defect in the build systems abstraction wrt to Builders. Yet, I think this is only relevant to ghc-cabal, and as such if there is no need for ghc-cabal anymore, this would be a no-issue for now.

**Comment by ndmitchell** [comment]
The issue we had in the past with merging ghc-cabal is that it requires a specific current directory, which is incompatible with parallelism as the pwd is a global shared resource.

**Comment by angerman** [comment]
Couldn't one use shakes resource management to ensure that no two invocations with different pwd's are running at the same time? That would of course restrict parallelism a bit. On the other hand, maybe this could be fixed in Cabal proper.

**Comment by ndmitchell** [comment]
Shakes resource is more fine grained than that, you have to say which rules conflict, and this will conflict with everything. The correct thing to do is fix cabal, but if you want the grim in Shake it should be possible - let me know.

**Comment by snowleopard** [comment]
The above commit seems to have fixed this issue, at least now the build completes with `-DCABAL_PARSEC`. 

I'm closing this issue, but if I missed anything, please reopen
