### ISSUE TITLE
Ideas to improve "Your first build"

### ISSUE THREAD

**Issue by duog** [snowleopard/hadrian#428]
I tried hadrian yesterday, and I found my first build to be more difficult than it needs to be.

It seems that build.sh requires that I have shake et al installed in my global/user package databases, which I hardly remember how to do :). 

build.cabal.sh seems to work perfectly, as long as cabal-install is installed.

build.stack.sh requires that I have nix installed. I don't grok nix yet, so I added --no-nix to the `stack build` command in build.stack.sh, and that worked perfectly too.

I would like to see something like:
*  If you have cabal in your path, run build.cabal.sh
*  If you prefer stack, run `build.stack.sh`. By default this uses stack's nix functionality to pull in tools used to build ghc such as autoconf and perl, if you'd rather not use nix, run `build.stack.sh --no-nix` [N.B. this would have to be added]
* If you'd prefer to build without cabal and nix, ensure [shake et al] are installed in your global or user package databases and run `build.sh`

Might I also suggest that showing "boxes" per file is not the best default, it took me too long how to pass `--progress-info=Brief`.

**Comment by ndmitchell** [comment]
For info, I have a standard list at http://neilmitchell.blogspot.co.uk/2016/03/compiling-ghc-on-windows.html (it might be a bit out of date, but it's ballpark). Thanks for sharing your initial experiences - we each only get one first view, and it's very valuable information we can't get on our own!

I agree about the boxes!

**Comment by snowleopard** [comment]
@duog Many thanks, I completely agree that we need to improve "Your first build"!

Parts of this has already been discussed elsewhere, e.g. see #301.

What about the following slightly revised plan?

* Delete `build.sh`. It looks like it no longer serves any purpose, e.g. all CIs use cabal or stack scripts.

* Rename `build.cabal.sh` to `build.sh` and add a Windows alternative `build.bat`. This will be the default way to run Hadrian.

* Make `build.stack.sh` non-nix by default and add `build.stack.nix.sh` so it's obvious from the names what does what. 

* Make `--progress-info=Brief` default. I kept boxes as the default because boxes are useful when working on Hadrian, but less so for Hadrian users.

**Comment by duog** [comment]
Sounds great @snowleopard, the current build.cabal.* does seem the most robust way to use hadrian.

**Comment by snowleopard** [comment]
@duog Great! Could you help with the Unix-specific scripts? I will then take care of Windows-specific scripts and documentation.

**Comment by snowleopard** [comment]
I've taken care of the `--progress-info` flag in the above commit.

**Comment by duog** [comment]
Sure, will do

**Comment by duog** [comment]
Sorry about all that commit spam :/ didn't realise that was going to happen

**Comment by snowleopard** [comment]
Thanks @duog, I'll complete this issue in a few days.

**Comment by izgzhen** [comment]
README.md needs to be revised as well by the way

**Comment by snowleopard** [comment]
@izgzhen Yes, sure. Other docs in `doc/*` may need to be checked as well. I'll take care of this.

**Comment by snowleopard** [comment]
I think I've done all we planned for this issue, so we can now close it. Do reopen if I forgot anything.
