### ISSUE TITLE
Document how to build a stage 3 compiler

### ISSUE THREAD

**Issue by bgamari** [snowleopard/hadrian#461]
How does one do this?

**Comment by snowleopard** [comment]
I don't think I've ever tried this actually. Will give it a try!

**Comment by bgamari** [comment]
Do note that GHC's `make` build system is actually broken in this regard (see [#14469](https://ghc.haskell.org/trac/ghc/ticket/14469#ticket)). Hopefully Hadrian will be able to do better here.

**Comment by bgamari** [comment]
After explicitly building,
```
_build/stage2/compiler/ghc_boot_platform.h
```
`hadrian inplace/bin/ghc-stage3` finishes. However, it only builds the `ghc-bin` executable linked against the `ghc` package built by Stage1.

It seems to me like we should have three distinct package databases:
 * a stage0 database containing only things built by the stage0 GHC
 * a stage1 database containing only things built by the stage1 GHC
 * if we build a stage3: a stage2 database containing only things built by the stage2 GHC

**Comment by snowleopard** [comment]
@bgamari This looks like something that should be easier to implement once @angerman completes #445.

**Comment by snowleopard** [comment]
@bgamari Do you know if there is any difference in command line arguments passed to various builders when building Stage2 and Stage3? If no, I think one could try to build Stage3 GHC simply by asking Hadrian to build the right target. 

P.S.: My current Hadrian set up is broken due to the Cabal bug in #634, so I haven't build GHC for a while. Somehow the workaround used by CI didn't work for me, but I guess I should give it another try.

**Comment by snowleopard** [comment]
I believe this has been fixed.
