### ISSUE TITLE
Hadrian's wall is broken

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/hadrian#501]
@izgzhen It looks like your Hadrian's wall project is abandoned. Could you confirm? Any chance to revive it?

Opening the issue here, since the https://github.com/izgzhen/hadrians-wall is archived.

**Comment by izgzhen** [comment]
Hi, I stopped maintaining it a few months ago since the AWS billing was a bit formidable for me. Regrading the infra code, the ease of using it is no comparison to more mature solutions like builtbot, teamcity, etc (once tried jenkins for Hadrian's Wall as well).

However, an ad-hoc CI system has two benefits:

- we can post-process of the build log with relative ease (no need to understand the log DB structure of any established CI tool)
- we can customize for Hadrian's need, esp. the architecture/platform part. I suspects the major open source CI tool can support multi-arch/platform easily. And it is also hard to cover all possible user environment.

I would like to revive it, but the major problem is that AWS was a bit expensive for me. And second, I was wondering if we can improve on the second point.

**Comment by izgzhen** [comment]
I wonder if GHC HQ has any plan about Hadrian nightly builders? @bgamari

**Comment by snowleopard** [comment]
@izgzhen Thank you! I didn't realise you had to pay for Hadrian's wall to AWS. Of course, we should find an alternative solution.

**Comment by bgamari** [comment]
Zhen Zhang <notifications@github.com> writes:

> I wonder if GHC HQ has any plan about Hadrian nightly builders? @bgamari
>
So currently we have a [compile-only CircleCI
build](https://circleci.com/gh/ghc/ghc/1651) run on every GHC
commit. As described on the
[Wiki](https://ghc.haskell.org/trac/ghc/wiki/ContinuousIntegration)
GHC's CI will ultimately be moving to a combination of Appveyor and
CircleCI. However, there are still a variety of questions that need to
be answered before we can switch over.

**Comment by izgzhen** [comment]
@snowleopard though I've got some ideas of improving it, but for now, I simply reignited the site: http://hadrians-wall.monad.systems

**Comment by snowleopard** [comment]
@izgzhen Thank you! If you spot that things got worse from one build to another, please shout.

**Comment by snowleopard** [comment]
Since the Hadrian's Wall repo and website are now live, I'm closing this issue.
