### ISSUE TITLE
Using Depreciated Module Distribution.PackageDescription.Parse

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#512]
The code is using module ‘Distribution.PackageDescription.Parse’ which is apparently depreciated in Cabal 2.1.0. Hence it is returning this error

src/Hadrian/Haskell/Cabal/Parse.hs:18:1: error:
    Failed to load interface for ‘Distribution.PackageDescription.Parse’
    It is a member of the hidden package ‘Cabal-2.0.1.1’.
    Perhaps you need to add ‘Cabal’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘Cabal-1.24.2.0’.
    Perhaps you need to add ‘Cabal’ to the build-depends in your .cabal file.
I believe this will be useful:
https://github.com/haskell/cabal/wiki/2.2-migration-guide
@snowleopard

**Comment by snowleopard** [comment]
@chitrak7 It looks like Hadrian submodule in GHC has fallen quite behind Hadrian HEAD, so I've just updated the submodule: https://github.com/ghc/ghc/commit/bf3f0a6808b89504a993dc9f2839daff9eaf6f2a.

This issue you refer to here has been fixed in #498.

Thanks for reporting! In future you can just do `git pull https://github.com/snowleopard/hadrian.git` in the Hadrian subdirectory of GHC to bring the submodule in sync with the HEAD.
