### ISSUE TITLE
move ghc-iserv to lib/bin

### ISSUE THREAD

**Issue by chitrak7** [snowleopard/hadrian#600]
For validation, the testsuite looks for ghc-iserv in lib/bin. This is causing near 200 validation failures.
@angerman @snowleopard

**Comment by snowleopard** [comment]
@angerman What do you think? I'm on Windows, so I don't think I even build `iserv` on my machine.

**Comment by izgzhen** [comment]
the location is `_build/stage1/bin/ghc-iserv` on my Linux machine by the way

**Comment by angerman** [comment]
This needs to be parameterized. Especially as this will likely move someplace into `utils/iserv.../` soon.

**Comment by angerman** [comment]
In general, we should try not to bend the layout for the testsuite, but adapt the testsuite to the new layout. Again this may need to be parameterized so that the old (make), and new (shake) based buildsystems both work.

**Comment by snowleopard** [comment]
@angerman See my comment here: https://github.com/snowleopard/hadrian/issues/592#issuecomment-388612287. I don't think I've ever seen any explanation for the rationale behind moving things to `bin`. If this is a useful feature, there should be a corresponding issue/PR that takes care of testsuite as well.

**Comment by chitrak7** [comment]
@snowleopard @angerman Current make system does not seem to take the location of ghc-iserv as an argument. I am looking further into this matter, but as of now, path to every other dependency can be specified as an argument (compiler, check-ppr, hp2ps, hsc etc), but not ghc-iserv.

**Comment by alpmestan** [comment]
I agree with @angerman that we ideally want this to be configurable. It should not be too hard to add an option for pointing to the iserv binary. I would however understand it if you decide to move the binary under `lib/bin` _for now_, so that @chitrak7 can make progress on the validation task. I might in fact look into this myself, I think I know what needs to be done in the testsuite driver.

@chitrak7 Do you think you could create a (GHC Trac) ticket with a summary of the problems you get when ghc-iserv is not under lib/bin/, with instructions to reproduce (just `hadrian validate`?) and assign it to me (I'm `alpmestan` on trac) ? Thanks!

**Comment by snowleopard** [comment]
Just an update: `iserv` has been moved in GHC and I made the necessary changes in Hadrian in https://github.com/snowleopard/hadrian/commit/8dba6748e84c632c3c0302620c3e62c9fcc3e948.

**Comment by chitrak7** [comment]
I think we can close it now. The issue has been taken care of!!
